---
- hosts: all
  remote_user: pi
  sudo: yes
  environment:
    http_proxy: http://10.0.0.1:8888
  tasks:

  
    # this does the equivalent of "install_dependencies.sh"
    - file: path=/etc/apt/sources.list.d/gstreamer.list state=absent
    - apt_repository: repo='deb http://vontaene.de/raspbian-updates/ . main' state=present update_cache=yes

    - apt: name=libmpg123-dev
    - apt: name=alsa-base
    - apt: name=alsa-tools
    - apt: name=alsa-utils
    - apt: name=libupnp-dev
    - apt: name=automake
    - apt: name=cvs
    - apt: name=libavcodec-dev
    - apt: name=libavformat-dev
    - apt: name=libavutil-dev
    - apt: name=libswscale-dev
    - apt: name=libasound2-dev
    - apt: name=libxmu-dev
    - apt: name=libxxf86vm-dev
    - apt: name=g++
    - apt: name=libgl1-mesa-dev
    - apt: name=libglu1-mesa-dev
    - apt: name=libraw1394-dev
    - apt: name=libudev-dev
    - apt: name=libdrm-dev
    - apt: name=libglew-dev
    - apt: name=libopenal-dev
    - apt: name=libsndfile-dev
    - apt: name=libfreeimage-dev
    - apt: name=libcairo2-dev
    - apt: name=libgtk2.0-dev
    - apt: name=python-lxml
    - apt: name=python-argparse
    - apt: name=libfreetype6-dev
    - apt: name=libassimp-dev
    - apt: name=portaudio19-dev
    - apt: name=libssl-dev
    - apt: name=libpulse-dev
    - apt: name=libgtk2.0-dev
    - apt: name=libgstreamer1.0-dev
    - apt: name=libgstreamer-plugins-base1.0-dev
    - apt: name=gstreamer1.0-pulseaudio
    - apt: name=gstreamer1.0-x
    - apt: name=gstreamer1.0-plugins-bad
    - apt: name=gstreamer1.0-alsa
    - apt: name=gstreamer1.0-plugins-base
    - apt: name=gstreamer1.0-plugins-good
    - apt: name=1.0-omx
